# Generated by Django 5.2.4 on 2025-08-13 14:48

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50, verbose_name='상가업소번호')),
                ('business_code', models.CharField(max_length=100, verbose_name='분류코드')),
                ('business_types', models.CharField(max_length=100, verbose_name='분류명')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('region_code', models.CharField(max_length=100, verbose_name='법정동코드')),
                ('region', models.CharField(max_length=100, verbose_name='법정동명')),
                ('floor', models.PositiveSmallIntegerField(null=True, verbose_name='층정보')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('monthly_rent', models.PositiveIntegerField(verbose_name='월세(만원)')),
                ('deposit', models.PositiveIntegerField(default=0, verbose_name='보증금(만원)')),
                ('daily_footfall_avg', models.PositiveIntegerField(default=0, verbose_name='일평균 유동인구')),
            ],
            options={
                'verbose_name': '후보 입지',
                'verbose_name_plural': '후보 입지 목록',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=api.models.generate_uuid, editable=False, max_length=32, verbose_name='방문자 UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='업종명')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.businesstype')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('A', 'Plan A'), ('B', 'Plan B')], max_length=1, verbose_name='플랜')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='입력 좌표(lon/lat)')),
                ('longitude', models.FloatField(verbose_name='입력 좌표(lon/lat)')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='입력 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 시각')),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_requests', to='api.businesstype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='api.user')),
            ],
            options={
                'verbose_name': '분석 요청',
                'verbose_name_plural': '분석 요청 내역',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='analysis_photos/%Y/%m/%d', verbose_name='이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.analysisrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='추천 점수')),
                ('description', models.TextField(verbose_name='추천 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.analysisrequest')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.businesstype')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.data')),
            ],
            options={
                'verbose_name': '추천 결과',
                'verbose_name_plural': '추천 결과 목록',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recommendation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
            ],
            options={
                'verbose_name': '추천-태그 연결',
                'verbose_name_plural': '추천-태그 연결 목록',
                'unique_together': {('recommendation', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.user')),
            ],
            options={
                'verbose_name': '즐겨찾기',
                'verbose_name_plural': '즐겨찾기 목록',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'recommendation'), name='uniq_favorite_user_recommendation')],
            },
        ),
    ]
