# Generated by Django 5.2.4 on 2025-08-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateSpot',
            new_name='Data',
        ),
        migrations.RenameModel(
            old_name='Visitor',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='plan',
            field=models.CharField(choices=[('A', 'Plan A'), ('B', 'Plan B')], max_length=1, verbose_name='플랜'),
        ),
        migrations.RenameField(
            model_name='analysisrequest',
            old_name='visitor',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='visitor',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='candidate_spot',
            new_name='spot',
        ),
        migrations.RenameIndex(
            model_name='data',
            new_name='api_data_point_40bc11_idx',
            old_name='api_candida_point_0fb0e0_idx',
        ),
        migrations.RenameIndex(
            model_name='data',
            new_name='api_data_monthly_0abada_idx',
            old_name='api_candida_monthly_976c65_idx',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='입력 주소'),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='업종명'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(verbose_name='추천 사유'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='태그명'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recommendation'), name='uniq_favorite_user_recommendation'),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
