# Generated by Django 5.2.4 on 2025-08-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='uuid',
            new_name='code',
        ),
    ]
