# Generated by Django 5.2.4 on 2025-08-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_uuid_data_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendationtag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recommendationtag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
