# Generated by Django 5.2.4 on 2025-08-14 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recommendationtag_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteSpot', to='api.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteSpot', to='api.user')),
            ],
            options={
                'verbose_name': '즐겨찾기 위치',
                'verbose_name_plural': '즐겨찾기 위치',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteType', to='api.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteType', to='api.user')),
            ],
            options={
                'verbose_name': '즐겨찾기 업종',
                'verbose_name_plural': '즐겨찾기 업종',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
