# Generated by Django 5.2.4 on 2025-08-18 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_favoritespot_favoritetype_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='analysis_request',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='recommendationtag',
            name='recommendation',
        ),
        migrations.AlterField(
            model_name='favoritespot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_spot', to='api.user'),
        ),
        migrations.AlterField(
            model_name='favoritetype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_type', to='api.user'),
        ),
        migrations.CreateModel(
            name='SpotRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='추천 점수')),
                ('description', models.TextField(blank=True, default='', verbose_name='추천 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_recommendations', to='api.analysisrequest')),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spot_recommendations', to='api.businesstype')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_recommendations', to='api.data')),
            ],
            options={
                'verbose_name': '위치 추천 결과',
                'verbose_name_plural': '위치 추천 결과 목록',
                'ordering': ['-score'],
            },
        ),
        migrations.AlterField(
            model_name='favoritespot',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.spotrecommendation'),
        ),
        migrations.CreateModel(
            name='TypeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='추천 점수')),
                ('description', models.TextField(blank=True, null=True, verbose_name='추천 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_recommendations', to='api.analysisrequest')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_recommendations', to='api.businesstype')),
            ],
            options={
                'verbose_name': '업종 추천 결과',
                'verbose_name_plural': '업종 추천 결과 목록',
                'ordering': ['-score'],
            },
        ),
        migrations.AlterField(
            model_name='favoritetype',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.typerecommendation'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='RecommendationTag',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
