# Generated by Django 5.2.4 on 2025-08-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_recommendation_analysis_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstype',
            name='parent',
        ),
    ]
