# Generated by Django 5.2.4 on 2025-08-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_businesstype_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotrecommendation',
            name='check_save',
            field=models.BooleanField(default=1, verbose_name='저장 여부'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typerecommendation',
            name='check_save',
            field=models.BooleanField(default=1, verbose_name='저장 여부'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotrecommendation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='추천 사유'),
        ),
    ]
