# Generated by Django 5.2.4 on 2025-08-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_spotrecommendation_check_save_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrequest',
            name='plan',
        ),
    ]
